#!/usr/bin/env python3
"""
    This is a command-line tool to list all the tags in a Quiver file

    Usage:
        qvls <quiver_file>
"""

import os
import sys

from quiver import Quiver

quiver_file = sys.argv[1]

qv = Quiver(quiver_file, "r")

for tag in qv.get_tags():
    print(f"{tag}")
